extern const Gfx RCP_luigi_head1[];
extern const Gfx RCP_luigi_head2[];
extern const Gfx RCP_luigi_head3[];
extern const Gfx RCP_luigi_head4[];
extern const Gfx RCP_luigi_head5[];
extern const Gfx RCP_luigi_head6[];
extern const Gfx RCP_luigi_head7[];
extern const Gfx RCP_luigi_head8[];
extern const Gfx RCP_swim_hand_l[];
extern const Gfx RCP_swim_hand_r[];
extern const Gfx RCP_luigi_near_body[];
extern const Gfx RCP_luigi_near0[];
extern const Gfx RCP_luigi_near1[];
extern const Gfx RCP_luigi_near2[];
extern const Gfx RCP_luigi_near3[];
extern const Gfx RCP_luigi_near4[];
extern const Gfx RCP_luigi_near5[];
extern const Gfx RCP_luigi_near6[];
extern const Gfx RCP_luigi_near7[];
extern const Gfx RCP_luigi_near8[];
extern const Gfx RCP_luigi_near9[];
extern const Gfx RCP_luigi_near10[];
extern const Gfx RCP_luigi_near11[];
extern const Gfx RCP_luigi_near12[];
extern const Gfx RCP_luigi_near13[];
extern const Gfx RCP_luigi_near14[];
extern const GeoLayout luigi_geo[];
extern const GeoLayout RCP_TitleLuigi[];
extern u16 l_mark_txt[32*32];
extern u16 l_momi_txt[32*32];
extern u16 l_hige_txt[32*32];
