extern const GeoLayout examplelogo_geo[];
extern Lights1 examplelogo_Red_lights;
extern Lights1 examplelogo_Blue_lights;
extern Lights1 examplelogo_Green_lights;
extern Vtx examplelogo_DrawCall_48_mesh_vtx_0[375];
extern Gfx examplelogo_DrawCall_48_mesh_tri_0[];
extern Vtx examplelogo_DrawCall_48_mesh_vtx_1[259];
extern Gfx examplelogo_DrawCall_48_mesh_tri_1[];
extern Vtx examplelogo_DrawCall_48_mesh_vtx_2[139];
extern Gfx examplelogo_DrawCall_48_mesh_tri_2[];
extern Gfx mat_examplelogo_Red[];
extern Gfx mat_examplelogo_Blue[];
extern Gfx mat_examplelogo_Green[];
extern Gfx examplelogo_DrawCall_48_mesh[];
extern Gfx examplelogo_material_revert_render_settings[];
