extern const GeoLayout title_player_platform_geo[];
extern Lights1 title_player_platform_Platform_lights;
extern Lights1 title_player_platform_Shadow_lights;
extern u8 title_player_platform_SUPER_MARIO_64_F0A134BD_3_2_all_ia8[];
extern u8 title_player_platform_SUPER_MARIO_64_A44DF3E3_3_1_all_ia8[];
extern Vtx title_player_platform_PLATFORM_mesh_vtx_0[31];
extern Gfx title_player_platform_PLATFORM_mesh_tri_0[];
extern Vtx title_player_platform_PLATFORM_mesh_vtx_1[4];
extern Gfx title_player_platform_PLATFORM_mesh_tri_1[];
extern Gfx mat_title_player_platform_Platform[];
extern Gfx mat_title_player_platform_Shadow[];
extern Gfx mat_revert_title_player_platform_Shadow[];
extern Gfx title_player_platform_PLATFORM_mesh[];
extern Gfx title_player_platform_material_revert_render_settings[];
